model_name: iris_classifier
version: 1.0.0
features:
  - sepal_length
  - sepal_width
  - petal_length
  - petal_width
preprocessing:
  scaler: StandardScaler
split:
  test_size: 0.2
  random_state: 42
hyperparameters:
  C: 1.0
  kernel: rbf
