name: build-and-deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Match this with your local Jupyter version

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter mlflow

      - name: ⚙️ Run Jupyter notebook
        run: |
          jupyter nbconvert --to notebook --execute test.ipynb --output executed_notebook.ipynb

      - name: 🚀 Commit & push executed notebook
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add executed_notebook.ipynb
          git commit -m "Executed notebook from GitHub Actions" || echo "Nothing to commit"
          git push origin main
