# .github/workflows/deploy.yml
name: MLflow Model CI/CD

on:
  push:
    branches: [ main ]  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training and log with MLflow
        run: |
          python train.py  # Replace with your actual script

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: ./models/  # or wherever you save models

      
